### PR TITLE
Update appveyor.yml

### PR DESCRIPTION
**Pull request by kdw503**

### CODE REVIEW

**Comment by timholy** [comment]
Do you need appveyor? #7 passed, you can merge it and just delete the appveyor webhook (go to Settings -> webhooks)

**Comment by timholy** [comment]
Oh, but you'd have to add `windows-latest` to the CI workflow script.

**Comment by kdw503** [comment]
You mean I can just add window-latest in the CI.yml and delete old appveyor.yml file, right?

**Comment by timholy** [comment]
Yep, exactly. Then once it merges you can delete the webhook.

**Comment by kdw503** [comment]
Should we delete .codecov.yml also?

**Comment by timholy** [comment]
> Should we delete .codecov.yml also?

It depends; do you want coverage notification comments on PRs? https://docs.codecov.io/docs/pull-request-comments
You can see a real-world example here: https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/463 (as long as you click on that link before the PR merges or closes). 

The main role of coverage notifications is to notify you about how your changes modify the testing coverage. If no one is going to look at them before deciding to merge, we should not have them; but if you'd find that helpful, and might add tests to a PR because of it, then we should have them. Deleting the `.codecov.yml` is asking them to send notifications.

**Comment by kdw503** [comment]
I misunderstood that `- uses: codecov/codecov-action@v1` line in the `CI.yml` can replace the old `.codecov.yml`.

**Comment by timholy** [comment]
Oh, yes, you probably could set the `comment` value from the `with:` section. https://github.com/codecov/codecov-action

**Comment by kdw503** [comment]
It looks there is no such option or similar option. Then, we need to keep the `.codecov.yml` file.

**Pull request closed without merging**
